[package]
name = "tile"
version = "0.1.0"
authors = ["The Reticle developers"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
io = { path = "../io" }
asm = { path = "../../langs/asm" }
regex = "1.3.9"
lazy_static = "1.4.0"
